# Generated by Django 4.2.1 on 2024-10-04 12:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 to 14 digits, optionally starting with +.', regex='^\\+?\\d{10,14}$')]),
        ),
    ]
