# Generated by Django 4.2.1 on 2024-10-08 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='degree_end_date',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='degree_start_date',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='field_of_study',
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=255)),
                ('professional_group', models.CharField(max_length=255)),
                ('professional_subgroup', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='users.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishment_name', models.CharField(max_length=255)),
                ('field_of_study', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('degree_start_date', models.DateField()),
                ('degree_end_date', models.DateField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='users.candidate')),
            ],
        ),
    ]
