# Generated by Django 4.2.1 on 2024-10-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_candidate_educations_candidate_experiences_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=255)),
                ('professional_group', models.CharField(max_length=255)),
                ('professional_subgroup', models.CharField(max_length=255)),
                ('custom_qualification', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='job_titles',
        ),
        migrations.AddField(
            model_name='company',
            name='job_titles',
            field=models.ManyToManyField(to='users.jobtitle'),
        ),
    ]
