# Generated by Django 4.2.1 on 2024-10-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_jobtitle_remove_company_job_titles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='job_titles',
            field=models.ManyToManyField(blank=True, related_name='companies', to='users.jobtitle'),
        ),
    ]
