# Generated by Django 4.2.1 on 2024-10-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_company_job_titles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtitle',
            name='professional_group',
            field=models.CharField(blank=True, choices=[('DEVELOPMENT', 'Development'), ('DESIGN', 'Design'), ('MANAGEMENT', 'Management'), ('SALES', 'Sales'), ('MARKETING', 'Marketing'), ('RESEARCH', 'Research')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jobtitle',
            name='professional_subgroup',
            field=models.CharField(blank=True, choices=[('BACKEND', 'Backend'), ('FRONTEND', 'Frontend'), ('FULLSTACK', 'Fullstack'), ('UI_UX', 'UI/UX Design'), ('PROJECT_MANAGEMENT', 'Project Management'), ('DATA_ANALYSIS', 'Data Analysis')], max_length=30, null=True),
        ),
    ]
