# Generated by Django 4.2.1 on 2024-10-08 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_jobtitle_professional_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='job_titles',
        ),
    ]
