# Generated by Django 4.2.1 on 2024-10-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_company_job_titles'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='job_titles',
            field=models.ManyToManyField(blank=True, related_name='companies', to='users.jobtitle'),
        ),
    ]
