# Generated by Django 4.2.1 on 2024-10-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_company_job_titles'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtitle',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='job_titles_related', to='users.company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='job_titles',
            field=models.ManyToManyField(blank=True, related_name='companies_related', to='users.jobtitle'),
        ),
    ]
