# Generated by Django 4.2.1 on 2024-10-08 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_jobtitle_companies_alter_company_job_titles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='qualifications',
        ),
    ]
