# Generated by Django 4.2.1 on 2024-10-08 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_company_qualifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='qualifications',
            field=models.JSONField(default=list),
        ),
    ]
