# Generated by Django 4.2.1 on 2024-10-08 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_company_qualifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobtitle',
            name='companies',
        ),
    ]
